### PR TITLE
Adds benchmark results

### PR DESCRIPTION
**Pull request by eliasjpr**

### CODE REVIEW

**Comment by elorest** [comment]
Do you think we should specify that it's with all optional pipes disabled and just returning "hello world"?

**Comment by eliasjpr** [comment]
I don't know how specific you would like to be you ran the benchmark, I think you should add anything that you consider important in regards to the benchmark

**Comment by elorest** [comment]
Ok. Specifically just the 2 things I said but I can add those when I get
home.

**Comment by eliasjpr** [comment]
Sounds good, I will merge this and then you can open a PR with the additional stuff

**Comment by elorest** [comment]
:+1:

**Comment by eliasjpr** [comment]
kk

**Pull request merged**
