### PR TITLE
Removes Singeleton Pattern from Handlers

### PR DESCRIPTION
**Pull request by eliasjpr**
### Description of the Change

Currently handlers are following the singleton pattern. Singleton pattern is not necessary for handlers since handlers are initialized only once per pipileline.

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Benefits

- Removes uncessary code.
- Makes it easy to maintain 
- Less complexity 
- Less code.

### CODE REVIEW

**Comment by drujensen** [comment]
Remove this old comment:

https://github.com/Amber-Crystal/Amber/blob/master/src/amber/router/pipe/base.cr#L5

**Comment by drujensen** [comment]
I don't think `self.config` will work anymore since you no longer have a singleton.  Consider removing this.
https://github.com/Amber-Crystal/Amber/blob/master/src/amber/router/pipe/base.cr#L11

**Comment by elorest** [comment]
@drujensen makes a good point. Having them as singletons allowed us to configure in initializers by yielding self of a singleton.

**Comment by elorest** [comment]
There's no reason we couldn't have a mix of singletons and normal instances. Session will probably need to stay a singleton because when I add encryption to sessions we're going to need to let them them choose to have it signed or encrypted and perhaps set session_key.

**Comment by eliasjpr** [comment]
@drujensen thank you for pointing out the comments and the config method. I did a quick lookup in the source code and  we are not making making use of the `config` method anywhere in code. 

We already are providing some config options on intiialize for the handlers that needs it.

```crystal
key = "blog.session"
secret = "Some awesome secret key"
signed = https? 

 pipeline :static do
    plug HTTP::StaticFileHandler.new "../examples/public", false
    plug Amber::Pipe::Session.new secret, key, singed
 end
```

@elorest I agree we can mix both but I see no need for singletons at this point.  We are not going to keep track of sessions in memory within the sessions handler, the session handler should only have responsibility of encoding and decoding session cookie strings. We need to create a `SessionAdapter or SessionStore` to provide an interface for tracking sessions in cookie (Current implementation), memory, db, or redis.

**Pull request merged**
