### PR TITLE
Get All App Routes

### PR DESCRIPTION
**Pull request by eliasjpr**
Currently there is no way to get all the routes define for the
application. Being able to find all the routes is beneficial for
developer reference.

This was added in order to get all the application routes and print them
in the console using the amber_cmd.

**Issue** https://github.com/Amber-Crystal/amber/issues/103

```bash
# User types the routes command
amber routes

# Example possible output generated by command
Available routes For Your App Name
+-----------+-------------------+--------------------+------------------------+
| HTTP Verb | Controller#Action | Helper (url, path) | Resource               |
+-----------+-------------------+--------------------+------------------------+
| GET       | photos#index      | photos_url/path    | /photos, /photos/index |
+-----------+-------------------+--------------------+------------------------+
| GET       | photos#new        | new_photo_url/path | /photos/new            |
+-----------+-------------------+--------------------+------------------------+
```

### CODE REVIEW

**Comment by elorest** [comment]
Does this effect anything performance wise or add complexity to the amber app its contained in? 

My strategy for this was going to be adding a very small subsection of route definition to amber_cmd and using it to translate `config/routes.cr` in the current directory to route string output... 

Your way is probably as good or better though. Thoughts?

**Comment by elorest** [comment]
Why are the commits all about cookies?

**Comment by eliasjpr** [comment]
Ha! I picked the wrong commit hash I'll fix it

**Comment by elorest** [comment]
Oh ok.

**Comment by eliasjpr** [comment]
@elorest this does not affect performance since the **all** method does not get used outside of the amber command line. Also, the Radix tree has a linked list is just matter of traversing should be fast.

**Pull request merged**
